export const SET_TOKEN = 'SET_TOKEN';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_LOCALE = 'SET_LOCALE';
export const SET_INIT_OPPORTUNITIES = 'SET_INIT_OPPORTUNITIES';
export const DROP_OPPORTUNITIES = 'DROP_OPPORTUNITIES';
export const ADD_OPPORTUNITIES = 'ADD_OPPORTUNITIES';
